name: Deployment
on:  
  push:
    branches:
      - main

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: yarn
      - name: Deploy to Storybook
        run: yarn deploy --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
