on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
