name: Lint
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
